SELECT 
    s.STUDY_INSTANCE_UID AS CASE_ID,
    s.CREATION_TIME AS FECHA_CREACION,
    s.STUDY_DATE AS FECHA_REALIZADO,
    s.REP_FINAL_TIMESTAMP AS FECHA_INFORMADO,
    TO_CHAR(s.CREATION_TIME, 'Day') AS DIA_CREACION,
    TO_CHAR(s.CREATION_TIME, 'Month') AS MES_CREACION,
    COALESCE(i.VAL_ID, 'N/A') AS PACIENTE,
    COALESCE(s.STUDY_MODALITY, 'N/A') AS MODALIDAD,
    COALESCE(s.ACCESSION_NUMBER, 'N/A') AS ACCESSION_NUMBER,
    COALESCE(s.REFERRING_PHYSICIAN_LAST_NAME, 'N/A') AS MEDICO_REFERENTE,
    COALESCE(s.STORING_AE, 'N/A') AS ALMACEN,
    COALESCE(s.REP_FINAL_SIGNED_BY, 'N/A') AS RECURSO_REPORTE,
    COALESCE(s.STUDY_DESCRIPTION, 'N/A') AS DESCRIPCION
FROM DIDB_STUDIES s
INNER JOIN DIDB_PATIENTS p ON p.PATIENT_DB_UID = s.PATIENT_DB_UID 
LEFT JOIN MDB_REP_CX_FIELD i ON p.MDL_PATIENT_DBID = i.DBID
WHERE s.STUDY_DATE >= '2020-01-01'
